name: "Build"
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v13
        with:
          name: maix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: traxys
      - run: nix build .#
      - run: nix flake check
